version: "3.8"

services:
  backend:
    image: <imagen del backend>
    container_name: ayd_backend
    restart: always
    depends_on:
      - db
    networks:
      - red_docker
  db:
    image: mysql:latest
    container_name: ayd_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: historicos
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - red_docker
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  red_docker:
volumes:
  mysql-data:
